# Generated by Django 5.2 on 2025-05-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
