# Generated by Django 5.2 on 2025-05-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='showcase/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
