# Generated by Django 5.2 on 2025-05-03 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_showcase_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Showcase',
        ),
    ]
