# Generated by Django 5.2 on 2025-05-03 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_showcaseimages_delete_showcase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShowcaseImages',
        ),
    ]
