# Generated by Django 5.2 on 2025-05-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodshowcase',
            name='image',
        ),
    ]
