# Generated by Django 5.2 on 2025-05-03 13:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_foodshowcase_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodshowcase',
            name='image_1',
            field=models.ImageField(default=3, upload_to='foodshowcase/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodshowcase',
            name='image_2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='foodshowcase2/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodshowcase',
            name='image_3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='foodshowcase3/'),
            preserve_default=False,
        ),
    ]
