# Generated by Django 5.2 on 2025-05-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_foodshowcase_image_1_foodshowcase_image_2_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodShowcase',
        ),
    ]
