# Generated by Django 5.2 on 2025-05-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0010_delete_foodshowcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodShowcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('image_1', models.ImageField(upload_to='foodshowcase/')),
                ('image_2', models.ImageField(upload_to='foodshowcase2/')),
                ('image_3', models.ImageField(upload_to='foodshowcase3/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
